name: test

on:

  push:

    branches:

      - main

jobs:

  production-deploy:

      runs-on: ubuntu-latest

      name: runTest

      steps:

      - uses: actions/checkout@v3

      - uses: bahmutov/npm-install@v1

      - run: npm run lint (Run ESLint)

      - run: npm run test (Run Jest)
